[tool.poetry]
name = "hyperschema-py"
version = "0.1.0"
description = ""
authors = ["TheCactusBlue <thecactusblue@gmail.com>"]
readme = "README.md"
packages = [{include = "hyperschema"}]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.4.2"
black = "^23.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
