// Generated by Hyperschema compiler. Do not edit manually!
import { z } from "zod";

export const Pet = z.object({
  name: z.string(),
});
type Pet = z.infer<typeof Pet>;

export const Person = z.object({
  name: z.string(),
  age: z.number().int(),
  isAwesome: z.boolean(),
  avatar: z.optional(z.string()),
  pet: z.array(Pet),
});
type Person = z.infer<typeof Person>;
