// Generated by Hyperschema compiler. Do not edit manually!
import { z } from "zod";

export const Pet = z.object({
  name: z.string(),
});
export type Pet = z.infer<typeof Pet>;

export const Person = z.object({
  name: z.string(),
  age: z.number().int(),
  isAwesome: z.boolean(),
  avatar: z.optional(z.string()),
  pet: z.array(Pet),
});
export type Person = z.infer<typeof Person>;

export class ChildService {
  readonly PATH = "child";
}

export class MainService {
  readonly PATH = "";
}
